### ISSUE TITLE
Disable ASC (Auto Self Calibration) per default

### ISSUE THREAD

**Issue by ghost** [paulvha/scd30#13]
Hi, just as an idea to be more accurate towards Sensirions information:

According to the documentation ([chapter 1.3.6](https://cdn.sparkfun.com/assets/d/c/0/7/2/SCD30_Interface_Description.pdf)) ASC is disabled by default in the sensor.

I think it could be very misleading, when the library will turn it on by default.
When not specifying anything else, it should behave like documented by the manufacturer.

**Comment by paulvha** [comment]
update added
