### ISSUE TITLE
BME280 not detected

### ISSUE THREAD

**Issue by Gedioa** [paulvha/scd30#2]
Hello, first let me say thanks for the library you have created. I love it!
I do have a question, i am unable to get the BME2180 sensor to be detected. 
I have the BME sensor connected with a breadbord the BME sensor scl is connected to D1 of my ESP-12 and the sda to D2. First i was thinking that the sensor was broken, but i got it working with the adafruit lib, i did had to change: #define BME280_ADDRESS  0x77, to:  #define BME280_ADDRESS  0x76 in the:  Adafruit_BME280.h file to get it to work.
So my questions:
1 Did i connected the BME280 sensor the right way?
2 do i have to make a change to the SparkFunBME280.h file to get it working? as my sensor uses the 0x76 address.

**Comment by Gedioa** [comment]
I am not sure if it is the way it needs to be done, but i have it working.
I added: 
`mySensor.settings.commInterface = I2C_MODE;
    mySensor.settings.I2CAddress = 0x76;`

just below `void setup()
{
  char buf[10];`

And now it is working

**Comment by paulvha** [comment]
your issue was that the default I2Caddress is 0x77, while your BME280 had 0x76. I have now added to example 10 a way to define the I2C address at the top so it can be set by the program without code changes.

**Comment by Gedioa** [comment]
Thanks for adding it.
